# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8cb24a2cf4e1d398bdcc2ce8bee3f8637b05f3002ada4a5bab719919c6ca65995aa2e3187195776fc0678c61e2a3fe058a80a6f82cf1f195940cfd478834e99

test:
  secret_key_base: 3617e3c6e5a1fa89da743b7c33f8752298b2f368ba32bff9f8f25f285030085a28ece1164f99ff47f7650142017103dee7cb640509fc97de3408e9f04b8fe6fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
